
GET http://localhost:5130/games


###

GET  http://localhost:5130/games/999

###
POST http://localhost:5130/games
Content-Type: application/json

{
    "name": "Dereje Abtew",
    "genreId": 3,
    "price": 40.65,
    "releaseDate": "2026-04-26"
}

###
PUT http://localhost:5130/games/1
Content-Type: application/json

{
  "name": "",
  "geners": "Fighting",
  "price": 6000,
  "releaseDate": "1991-02-01"
}

###
DELETE http://localhost:5130/games/1